### ISSUE TITLE
add ec console log button

### ISSUE THREAD

**Issue by WeirdTreeThing** [death7654/Chrultrabook-Windows-Controller#12]
would be pretty cool

**Comment by death7654** [comment]
- ec console log
- battery information (battery)
- ec flash chip information (chipinfo)
- flash information (flashinfo)
- SPI information (flashspiinfo)
- ec flash chip protocol info (protoinfo)
- temperature sensor info (tempsinfo)
- power delivery info (pdlog)

**Comment by death7654** [comment]
Its completed
